### ISSUE TITLE
falls back to the native ResizeObserver?

### ISSUE THREAD

**Issue by blurymind** [ZeeCoder/react-resize-observer#2]
this note on the readme says

> Uses resize-observer-polyfill internally, which falls back to the native ResizeObserver, if available.

How true is it?
When you go to 
https://github.com/que-etc/resize-observer-polyfill

That says that it's based on MutationObserver (https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver), not a native ResizeObserver ( https://developers.google.com/web/updates/2016/10/resizeobserver )

> Implementation is based on the MutationObserver and uses Mutation Events as a fall back if the first one is not supported, 

And second question - what is the difference between the two exactly - in terms of performance of many elements?

It would be nice you you had some sort of a stress test codepen with a 100 observers.

**Comment by ZeeCoder** [comment]
I'm basing that statement on this:
https://github.com/que-etc/resize-observer-polyfill/blob/1.5.0/src/index.js

**Comment by ZeeCoder** [comment]
Here's a quick demo:
https://codesandbox.io/s/eloquent-currying-wb9hh

On Chrome the boxes adjust instantly, while in FF lower levels adjust with a delay.

You can use codesandbox to create a stress test like that. 👍

**Comment by blurymind** [comment]
thank you :) I will close this, as it is not an issue
